### PR TITLE
CAN threads and CAN driver refactor

### PR DESCRIPTION
**Pull request by t-bre**

### CODE REVIEW

**Comment by t-bre** [comment]
@hashyaha Let me know if you're going to work on anything related to CAN. I'm currently re-structuring the CAN code to fit in with the RTOS which requires lots of big changes to the layout of the code and any other changes will be a pain to merge!

**Comment by t-bre** [comment]
@hashyaha Also wondered if you know what the purpose of the `<<` operations on the following lines in the PM100 analog voltage parser are:
```C
uint32_t temp = second32bits << 22; // 32-10
CAN_inputs[ANALOG_INPUT_4 + i] = temp >> 22;
second32bits = second32bits >> 10;
```
Is it to mask out the top 10 bits? Maybe its simpler to have it be a single immediate operation:
```C
CAN_inputs[ANALOG_INPUT_4 + i] = second32bits & (UINT32_MAX >> 10);
```

**Comment by hashyaha** [comment]
The purpose of the left shift is to extract the analogue voltage 10 bits by 10 bits
image
I think the right one-line expression to use here will be
```
CAN_inputs[ANALOG_INPUT_4 + i] = (second32bits >> (i*10)) & (UINT32_MAX >> 22);
```  
I can fix them on Tuesday

**Comment by t-bre** [comment]
Oh you're totally right its the lower 10 bits each time, I got that completely wrong 😬. I think it's fine as is in that case, no need to fix it. As a one liner it will probably still be compiled down to the same thing, I thought it could maybe be reduced to a single instruction but I was wrong!

**Pull request merged**
